# Generated by Django 4.2.11 on 2026-03-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_critical', models.BooleanField(default=False, help_text='If True, 100% of exercises must pass to validate this day.')),
                ('passing_threshold', models.PositiveIntegerField(default=80, help_text='Minimum percentage of exercises to pass (ignored if is_critical).')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('has_timeout', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('performance_notes', models.TextField(blank=True, help_text='Pedagogical notes about algorithmic complexity.')),
                ('starter_code', models.TextField(blank=True, help_text='Template code shown to the user.')),
                ('function_signature', models.CharField(blank=True, help_text="Expected function signature, e.g. 'fn add(a: i32, b: i32) -> i32'", max_length=500)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.day')),
            ],
            options={
                'ordering': ['day', 'number'],
                'unique_together': {('day', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Compilation Error'), ('timeout', 'Timeout')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises_passed', models.PositiveIntegerField(default=0)),
                ('total_exercises', models.PositiveIntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day')},
            },
        ),
    ]
