# Generated by Django 4.2.11 on 2026-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='examples',
            field=models.TextField(blank=True, help_text='Input/output examples for this exercise.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='function_signature',
            field=models.CharField(blank=True, help_text='Expected function signature.', max_length=500),
        ),
    ]
