# Generated by Django 4.2.11 on 2026-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_examples_alter_exercise_function_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='language',
            field=models.CharField(default='rust', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tutorial',
            field=models.TextField(blank=True, help_text='French tutorial for this exercise.'),
        ),
    ]
